#pragma once

#define EXTERN_OVERLAY_ID(index) extern unsigned int OVERLAY_##index##_ID;
#define OVERLAY_ID(index) ((unsigned int)&OVERLAY_##index##_ID)

#ifdef __cplusplus
extern "C" {
#endif

EXTERN_OVERLAY_ID(0)
EXTERN_OVERLAY_ID(1)
EXTERN_OVERLAY_ID(2)
EXTERN_OVERLAY_ID(3)
EXTERN_OVERLAY_ID(4)
EXTERN_OVERLAY_ID(5)
EXTERN_OVERLAY_ID(6)
EXTERN_OVERLAY_ID(7)
EXTERN_OVERLAY_ID(8)
EXTERN_OVERLAY_ID(9)
EXTERN_OVERLAY_ID(10)
EXTERN_OVERLAY_ID(11)
EXTERN_OVERLAY_ID(12)
EXTERN_OVERLAY_ID(13)
EXTERN_OVERLAY_ID(14)
EXTERN_OVERLAY_ID(15)
EXTERN_OVERLAY_ID(16)
EXTERN_OVERLAY_ID(17)
EXTERN_OVERLAY_ID(18)
EXTERN_OVERLAY_ID(19)
EXTERN_OVERLAY_ID(20)
EXTERN_OVERLAY_ID(21)
EXTERN_OVERLAY_ID(22)
EXTERN_OVERLAY_ID(23)
EXTERN_OVERLAY_ID(24)
EXTERN_OVERLAY_ID(25)
EXTERN_OVERLAY_ID(26)
EXTERN_OVERLAY_ID(27)
EXTERN_OVERLAY_ID(28)
EXTERN_OVERLAY_ID(29)
EXTERN_OVERLAY_ID(30)
EXTERN_OVERLAY_ID(31)
EXTERN_OVERLAY_ID(32)
EXTERN_OVERLAY_ID(33)
EXTERN_OVERLAY_ID(34)

#ifdef __cplusplus
}
#endif
